name: Flumina
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bwa=0.7.17
  - bioconductor-biostrings=2.66.0
  - fastp=0.23.4
  - gatk4=4.5.0.0
  - irma=1.0.3
  - lofreq=2.1.5
  - python=3.10.14
  - samtools=1.19
  - r-doparallel=1.0.17
  - r-ape=5.7_1
  - r-data.table=1.14.8
  - r-essentials=4.2
  - r-seqinr=4.2_30
  - r-stringr=1.5.0
  - r-foreach=1.5.2
  - snakemake=7.32.4
